services:
  - type: psql   
    name: skills-db
    plan: free

  - type: web   
    name: skills-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn manage:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skills-db
          property: connectionString
      - key: FLASK_APP
        value: manage.py